language: python
sudo: true
python:
  - "3.6"

services:
  - docker-compose

install:
  - docker login -u $D3M_REGISTRY_USER -p $D3M_REGISTRY_PASSWORD registry.datadrivendiscovery.org/
  - cd test
  - docker-compose up -d

script:
  - docker exec -it experimenter-test bash
  - travis_wait python3 run_tests.py
