language: python
sudo: true
python:
  - "3.6"

services:
  - docker-compose

install:
  - docker login -u $D3M_REGISTRY_USER -p $D3M_REGISTRY_PASSWORD registry.datadrivendiscovery.org/
  - cd test

script:
  - bash create_and_test.shd
