version: '3.3'
services:
  d3m:
    build: .
    container_name: experimenter
    stdin_open: true
    tty: true
    env_file:
    - .env
    entrypoint: /bin/bash
    volumes:
      - ${VOLUMES}:/volumes
      - ${DATASETS}:/datasets
      - ${EXPERIMENTER}:/d3m-experimenter

networks:
  host:
    external: true