version: '3.3'
services:
  d3m:
    build: .
    container_name: experimenter
    stdin_open: true
    tty: true
    env_file:
    - .env
    entrypoint: /bin/bash
    volumes:
      - ${DATASETS}:/datasets:z
      - ${EXPERIMENTER}:/d3m-experimenter:z

networks:
  host:
    external: true
