version: '3.3'
services:
  d3m:
    build: .
    container_name: experimenter
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
    volumes:
      - ${VOLUMES}:/volumes
      - ${DATASETS}:/datasets
      - ${EXPERIMENTER}:/d3m-experimenter
      - ${D3M}:/d3m

networks:
  host:
    external: true