version: '3.9'

services:
  database:
    image: 'redis:alpine'

  rq-dashboard:
    # TODO: create our own dockerfile
    image: 'eoranged/rq-dashboard:v0.6.3'
    command: '--redis-url redis://database'
    env_file:
      - ./.env
    ports:
      - target: '9181'
        published: '${DASHBOARD_PORT}'
